AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Example lambda implementations of API Gateway JSON responses
Globals:
  Function:
    Handler: main
    Runtime: go1.x
    Timeout: 5

Resources:
  IdentifyUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: examples-identify-user
      CodeUri: ./lambda
      Events:
        Request:
          Type: Api
          Properties:
            Method: GET
            Path: /hello